### ISSUE TITLE
swipe up / down to expand / collapse panel

### ISSUE THREAD

**Issue by natalyablanco** [trufi-association/trufi-core#166]
Design improvement

**Comment by mdoelker** [comment]
Swipe up already works. Swipe down collides with the scrollable itinerary. We should probably a draggable handle like this: 
![image](https://user-images.githubusercontent.com/2145319/66260073-185a1180-e7ba-11e9-910e-df5be3a6d120.png)

**Comment by md-weber** [comment]
Is this Issue still relevant @mdoelker?

**Comment by mdoelker** [comment]
Yeah, I guess it is
