### ISSUE TITLE
Option to hide search input fields

### ISSUE THREAD

**Issue by annikabock** [trufi-association/trufi-core#175]
Auf kleinen Displays kann dies sinnvoll sein. Zudem sieht man Start und Ziel nach dem Suchvorgang ja unten und benötigt die Info nicht dauerhaft im Sichtfeld.
Auch die Option, wie bei Google Maps mit einem Tap auf die Karte, die Sucheingabe und Suchergebnis aus- und wiedereinzublenden, finde ich ganz hilfreich.

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
