### ISSUE TITLE
starting without internet connection errors/confuses

### ISSUE THREAD

**Issue by annikabock** [trufi-association/trufi-core#176]
Wenn man ohne Netzzugang startet, aber die App nicht im Offline-Modus ist, kann man Start und Ziel aus "Zuletzt gesucht" oder "Orte" auswählen und sogar suchen (Ich vermute aus den Offline-Daten), aber bekommt nach dem Tap auf das jeweilige Suchergebnis den Dialog "Fehler / Keine Internetverbindung".
Aus Benutzersicht erscheint mir das nicht konsistent bzw. es wäre wohl konsequenter, dem User anzubieten, hier direkt in den Offline-Modus zu schalten oder ihn zumindest darüber zu informieren, dass der Online-Modus ohne Netzverbindung nicht funktioniert. Dies ließe sich ggf. auch direkt beim Start überprüfen und dem Nutzer mitteilen.

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
