### ISSUE TITLE
interrupt offline search if wanted

### ISSUE THREAD

**Issue by annikabock** [trufi-association/trufi-core#177]
Die Offline-Suche dauert relativ lange. Keine Ahnung, ob das an meinem S7 liegt, aber ich brauche hier fast immer länger als 10 Sekunden, teilweise mehr als 20 Sekunden. Falls das ein allgemeines Problem ist, wäre ein "Suche Abbrechen"-Button während des Vorgangs hilfreich.

**Comment by md-weber** [comment]
Hi, @annikabock @RaimundWege is this issue still relevant?

**Comment by annikabock** [comment]
not entirely sure - did you check if you can still reproduce the problem on any device?

**Comment by md-weber** [comment]
I just found so far the following Comment: ` // FIXME: For now we search locations always offline`
Therefore it sounds to me like there is currently just one search in the Trufi Core possible.

**Comment by annikabock** [comment]
hmm super long time ago and Raimund is unluckily is not working at ours anymore, but maybe not relevant anymore indeed

**Comment by md-weber** [comment]
To clean the repo a little, I would recommend closing this issue for now, and if we face the problem again, we reopen or create a new one. If this is ok for you?

**Comment by annikabock** [comment]
sure, thanks!
