### ISSUE TITLE
tiles are not rendered correctly when switching to online mode

### ISSUE THREAD

**Issue by annikabock** [trufi-association/trufi-core#178]
Beim Wechsel von Offline zu Online wird die Karte nicht gerendert, wenn ich "Auf der Karte auswählen" verwende. Zumindest fehlen Zoomstufen bzw. es werden nur die angezeigt, die ich vorher schon mal online geladen hatte. Mein Netzwerkmonitor auf dem Gerät zeigt mir auch, dass keine Daten heruntergeladen werden, wenn ich zoome oder hin -und herschiebe und Tiles fehlen.

**Comment by md-weber** [comment]
I tested a bit around and it seems that this issue is meanwhile resolved, feel free to reopen the issue if you still get the problem.
