### ISSUE TITLE
Strange behavior of the find place fields

### ISSUE THREAD

**Issue by SamuelRioTz** [trufi-association/trufi-core#193]
branch: develop
steps:

1. set language to english
2. choose the first field to "your location"
3. choose the second field any place
4. change language to spanish
5. choose the first field to "tu ubicacion"

issues:

- not translating "your location" option
- showing "map marker" instead "your location"
- showing "posicion en el mapa" instead "tu ubicacion"

**Comment by md-weber** [comment]
Is this still relevant @RaimundWege @SamuelRioTz, or can this issue be closed?

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
