### ISSUE TITLE
Which lines run near my position

### ISSUE THREAD

**Issue by annikabock** [trufi-association/trufi-core#21]
As passenger, I want to know which lines are passing by my current place.
Die Idee war so ein bißchen, dass man direkt nach dem Öffnen der App sieht, welche Linien grundsätzlich am Standort vorbeiführen.

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.

Internal future strategy: Attracting more women to work on technical tasks like @annikabock or @natalyablanco . Check reactivation of gender diversity.
