### ISSUE TITLE
Update ItinerarySummaryView and ItineraryDetailView

### ISSUE THREAD

**Issue by andreashelms** [trufi-association/trufi-core#218]
![401_route small](https://user-images.githubusercontent.com/21622725/51374987-ea864d00-1b04-11e9-9423-f2222da48029.png)
![501_route expanded](https://user-images.githubusercontent.com/21622725/51375001-f40fb500-1b04-11e9-9a01-ea5b4bbdba05.png)

**Comment by christophhanser** [comment]
Explanation in this PowerPoint: https://drive.google.com/open?id=1NXhZ84jVMrmmpOkKmOvso0Gwj7Y_lvH5

**Comment by mdoelker** [comment]
![image](https://user-images.githubusercontent.com/2145319/88053425-10f2d180-cb5c-11ea-93f2-adebb2eeb012.png)
Copied over visualization from Powerpoint

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
