### ISSUE TITLE
Add an explanation / hint when starting for the first time

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-core#257]
Add an explanatory text about the covered routes (and maybe how to contribute) when the app is started for the first time.

**Comment by md-weber** [comment]
We could add some Onboarding Screen that helps users identify how to work with the application.
![grafik](https://user-images.githubusercontent.com/8026644/114865532-a9b83400-9df2-11eb-9c52-a175f5f0f109.png)

It should be quite easy to implement, but we need to make sure that the Host Apps can change the texts.
https://pub.dev/packages/introduction_screen

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
