### ISSUE TITLE
Change menu item "Contributers" to "People"

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-core#259]
Two options:
1. Change "Contributers" to "People" (or something similar?) and have two sections in the screen: "Team" and "Contributers" (for people providing translations, routes,...)
2. Add seperate menu item "Team"

**Comment by md-weber** [comment]
Is this issue still relevant, or can it be closed? 
@christophhanser @mdoelker @hoodi

**Comment by md-weber** [comment]
I believe @RaimundWege already implemented that section. Therefore I will close this issue.
https://github.com/trufi-association/trufi-core/commit/7be42843657b0ecb54e8c79a7a8aa7b020c1ab3c
