### ISSUE TITLE
Update the menu: Add description (link) how to contribute

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-core#260]
When we have a proper "Contribute" page on the website we should put a link in the menu.

**Comment by md-weber** [comment]
Hi @hoodi, great idea. I will link the relevant issues to it.

Relevant Issues:
https://github.com/trufi-association/trufi-core/issues/404
https://github.com/trufi-association/trufi-core/issues/395

**Comment by md-weber** [comment]
We have now a Contribution and a Code of Conduct. Therefore I will close this issue.
