### ISSUE TITLE
Add price of the joureny

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-core#264]
We could add the price of the journey if this is possible at all.

**Comment by rmstaanaIT** [comment]
Would be great to have Zone-Base Fares

**Comment by christophhanser** [comment]
Hi,
how exactly would you like to have it? In which City? And how does it work
there?
Thanks, Christoph

**Comment by rmstaanaIT** [comment]
In Metro Manila, the fares are based on the distance.

Example:
COMPUTATION OF FARES: 
REGULAR 
 First Four (4) kilometers = P 8.00 
 Succeeding kilometers = Additional P 1.50 per kilometer 
STUDENT/ELDERLY/DISABLED ( 20% Discount ) 
 Succeeding kilometers = Additional P 1.20 per kilometer

**Comment by nicolelaine** [comment]
This issue should be placed in each individual repo.
