### ISSUE TITLE
Add advertising

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-core#265]
We could add ads to the app but this needs to be discussed.

**Comment by amenk** [comment]
One option would be to include a webview with a URL like `https://placeinfo.trufi.app/?lat=...&lon=...` which displays information about the target of a trip, including local businesses

**Comment by amenk** [comment]
What do you think about this form ob subtle ad placement (I think a webview would make it too obtrusive) 

![Selection_252](https://user-images.githubusercontent.com/1087128/71533710-a72e8400-28fa-11ea-821e-a63f2cc41b43.png)

**Comment by amenk** [comment]
The ad server could be as simple as returning a json
    { text: "(Ad)

**Comment by amenk** [comment]
> something like a device ID (to not always display the same ads -> but for data privacy reasons of
> the users a random installation ID would be best)

We should use the ne correlation ID :-)

https://github.com/trufi-association/trufi-app/commit/623ff5fd5d81048606fa7dce0a867a7d8a4d152a#diff-c04dfa7fa351a6a9c77cf2655a39bcb4R109
