### ISSUE TITLE
Try out mbtiles pull-request for flutter_map

### ISSUE THREAD

**Issue by RaimundWege** [trufi-association/trufi-core#277]
https://github.com/johnpryan/flutter_map/pull/240

**Comment by amenk** [comment]
Are we talking about raster or vector tiles?
For example, vector tiles for Cochabamba would "only" be 20 MB.

https://openmaptiles.com/downloads/tileset/osm/south-america/bolivia/cochabamba/

Maybe this map library can be used: https://github.com/tobrun/flutter-mapbox-gl

**Comment by RaimundWege** [comment]
@amenk the issue with mapbox (and google maps) is they're using just their native android and iOS implementation of the mapbox (or google maps) SDK. The flutter_map has the advantage that every marker is also a flutter widget and so we need to implement the map logic only once and it is also written in dart.

> Are we talking about raster or vector tiles?
For now we're using just raster tiles but in the mean time it could be possible to use vector tiles with a custom tile provider which is a new feature of the flutter_map package.

**Comment by md-weber** [comment]
Reading the Issue on Fleaflet it sounds like it is not yet supported, feel free to open the issue again if it is still relevant.

**Comment by amenk** [comment]
We are experimenting with vector tiles as @SamuelRioTz said that it is now possible to implement any map backend ... not sure how well it would work with the markers ? 

It does not make much sense to use the MapBox package, as we would run into Licensing issues if we try to publish on f-droid.
https://github.com/m0nac0/flutter-maplibre-gl looks promissing though ...

See also: https://github.com/AddisMap/yeneguzo-app/issues/4
