### ISSUE TITLE
Open all my map links from chats such as WhatsApp as a direct destination from where I am right now

### ISSUE THREAD

**Issue by christophhanser** [trufi-association/trufi-core#281]

**Comment by christophhanser** [comment]
When clicking on a place, we want also to show Trufi as potential app:

![image](https://user-images.githubusercontent.com/10851343/77833827-7e5b9c00-7140-11ea-84e4-115b0bcac93b.png)

**Comment by dileep9490** [comment]
Do you mean on clicking an link in some other app. It should open Trufi app and show in App's Map ?

**Comment by GustavoTCh** [comment]
@dileep9490 in this link you can find more information

**Comment by dileep9490** [comment]
To be honest I was actually searching about it
I need some clarity on the issue
Should it work like this-> on clicking the link we should launch the app as
intent or what?
