### ISSUE TITLE
Language files need to be generalized

### ISSUE THREAD

**Issue by christophhanser** [trufi-association/trufi-core#292]
"title": "Trufi App" => the title is unique across all languages, but different for each app, so we should have it saved some where else

"tag_line": "Public transportation in Cochabamba" => city should be removed here and made generic, so that Accra and other cities work as well

**Comment by mdoelker** [comment]
I'm not sure if we should pull this out of the translation files. Maybe it makes sense to externalize translations out of the core package that we want to build (#293)

**Comment by amenk** [comment]
Why not putting the cites as a variable? So most of the translations can be reused ...

**Comment by md-weber** [comment]
Without knowing this Issue I did exactly that, in Lokalise I added the cityName as a variable and it is now possible to pass that down. Thanks to the TrufiCustomTranslations it is now also possible to overwrite the Title.
