### ISSUE TITLE
Specific Routing issue: Huayllani -> Beauty Came involves swimming

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-core#314]
See the attached screenshots.

The routing seems to involve swimming through a river ;-)

![Screenshot_20190922-135709](https://user-images.githubusercontent.com/1087128/65427276-3ca90c00-de12-11e9-9a5e-5818487700b6.png)
![Screenshot_20190922-135719](https://user-images.githubusercontent.com/1087128/65427278-3ca90c00-de12-11e9-85e0-f031ac765809.png)

**Comment by mdoelker** [comment]
Seems we need a swimming icon for the itinerary then 😜

**Comment by amenk** [comment]
Seems this is a typical example of an bug report, without "What I expect to happen".

Just to clarify: I expect the route planning to be without swimming :-)

**Comment by mdoelker** [comment]
I was kidding. We have someone look into it who has more experience with the OTP backend. The routing is not done in the client.

**Comment by amenk** [comment]
Shall we post that at https://github.com/opentripplanner/OpenTripPlanner/issues ? 
What is the OTP version used? Is there a way to access the OTP Web-Frontend without Trufi for repro?

**Comment by mdoelker** [comment]
We are running 1.3.0 at the moment. I'll send you a link.

**Comment by mdoelker** [comment]
In my test it took the bridge though 
![image](https://user-images.githubusercontent.com/2145319/72225004-a8a9ae80-3580-11ea-96fa-78f7ca6441ad.png)

We should check OSM if there is something mapped incorrectly.

**Comment by amenk** [comment]
Did you try reproducing it using the Trufi App on Android? I can still reproduce it.

**Comment by md-weber** [comment]
The bug is still relevant, is there anything we can do on our side? @mdoelker 
![grafik](https://user-images.githubusercontent.com/8026644/114861806-09f8a700-9dee-11eb-9ea7-09c2e588ae4b.png)

**Comment by mdoelker** [comment]
@md-weber Frankly, I have no idea

**Comment by ValorNaram** [comment]
I can't reproduce this error in the app and also not in the backend. So this can be closed.
