### ISSUE TITLE
Search produces "red screen" (like Blue Screen on Windows)

### ISSUE THREAD

**Issue by christophhanser** [trufi-association/trufi-core#323]
After searching within the Trufi App for La Paz (build by @SamuelRioTz with debug mode), the following error occurs:

![image](https://user-images.githubusercontent.com/10851343/66237003-2fcec700-e6f4-11e9-88ac-fc73e7ffc916.png)

Produced with a tablet.

**Comment by christophhanser** [comment]
Happened on a Tab S2

**Comment by mdoelker** [comment]
I need a bit more explanation on how to reproduce this.

**Comment by nicolelaine** [comment]
This is a bug that happens in a development version.
