### ISSUE TITLE
Add bus operator to route instructions

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-core#343]
In Addis Ababa, we have different bus operators. It is important to see in the time schedule, which is the bus operator. The information is in agencyName in the field of the leg in the OTP response.

Should this be implemented in trufi_core or in the specific Addis Ababa app?

**Comment by christophhanser** [comment]
I would vote for Addis Abeba only since this requirement has not yet popped
up in the other cities.

**Comment by amenk** [comment]
@christophhanser Technically we still might need to implement it as an option in core that is switched of by default, I think.

@RaimundWege or did you plan another simple way to add such functionality to the custom app, which is based on the Trufi core package?

**Comment by christophhanser** [comment]
Now that you say it, I guess that this is the Technically correct approach.
:)

**Comment by amenk** [comment]
I will try to implement that --- we might not need an option, as api.trufi.app does not supply agency info, so I would just not display it, if the info is not there :)

**Comment by amenk** [comment]
tried to implement it (was pretty easy)... but it turns out that for some (bus) it makes sense to show the operator, for others (minibus) not. We will maybe just add the agency name to the route. I am closing this for now.

**Comment by amenk** [comment]
What we of course could do is, to define a schema for agency name, like "Offical Agency Name [Shortname]" and show the text from the brackets - if present - in the itinerary.

**Comment by md-weber** [comment]
Is this issue still relevant for the Core? @christophhanser @amenk

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
