### ISSUE TITLE
Add light rail (train/tram) support

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-core#347]
We should add support for GTFS route_type = 0 (Tram, Light Rail, Street Car) in the routing instructions, symbols and so on. This is needed for Addis Ababa Light Rail.

**Comment by amenk** [comment]
Working on a PR ...

**Comment by md-weber** [comment]
I think the PR is merged, so we support now Light Rail. I would close this Issue. @amenk @mdoelker
