### ISSUE TITLE
Automate taking screenshots for app stores

### ISSUE THREAD

**Issue by mdoelker** [trufi-association/trufi-core#355]
Use tool https://pub.dev/packages/screenshots
Integrate with fastlane #356

**Comment by amenk** [comment]
I tried to do that and I am able to do screenshots, see 

https://github.com/AddisMap/yeneguzo-app/tree/screenshot-tests

But I ran into this unsolved issue, where entering text is not possible due to problems with the on-screen keyboard:https://github.com/flutter/flutter/issues/15415

**Comment by amenk** [comment]
Also I saw, that the search results are missing when opening the location list (feels like search.json is not taken into account) - any clue where this could origin from?

**Comment by mdoelker** [comment]
Posting this for future reference https://medium.com/@nocnoc/automated-screenshots-for-flutter-f78be70cd5fd

**Comment by nicolelaine** [comment]
This issue should be part of each individual repo.

**Comment by amenk** [comment]
See https://github.com/trufi-association/trufi-core/issues/356#issuecomment-1007498492
