### ISSUE TITLE
Automate app store deployment

### ISSUE THREAD

**Issue by mdoelker** [trufi-association/trufi-core#356]
https://fastlane.tools/

**Comment by amenk** [comment]
So there is an XCode11 image on Travis which is nice ;-) I did not yet succeed in "fastlane init" for iOS https://travis-ci.org/AddisMap/yeneguzo-app/builds/633977131

Wondering if we should build Android images on iOS as well or on Linux.

**Comment by mdoelker** [comment]
Building Android on the mac image as well should be totally fine.

**Comment by amenk** [comment]
While that might mean to setup a full android toolchain on the OSX image. There are android images for Travis as well: https://docs.travis-ci.com/user/languages/android/
Meaning we have to setup flutter on OSX and on the Android image as well.

**Comment by mdoelker** [comment]
Ah okay. Alternative would be github actions. The mac image has Android SDK and build tools installed https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015

**Comment by amenk** [comment]
Trying currently with GiHub actions ... https://github.com/AddisMap/yeneguzo-app/commit/0a60c0f92683dc4153341fe9f97b069a78bdc277/checks?check_suite_id=391169858

**Comment by amenk** [comment]
Building and uploading to play store works https://github.com/AddisMap/yeneguzo-app/commit/2f0bfc671a7f9232e8285deb0466bcd891cb8533/checks?check_suite_id=395576066
Concerning iOS I have to figure out how to manage the certificates, see https://docs.fastlane.tools/best-practices/continuous-integration/

**Comment by amenk** [comment]
I think in iOS it will not be possible to update also store meta data ... because all apple IDs have two factor auth (I think)

https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

> Note: The application specific password will not work if your action usage does anything else 
than uploading the binary, e.g. updating any metadata like setting release notes or distributing to testers, etc.

**Comment by amenk** [comment]
I now also successfully pushes to AppStore:

https://github.com/AddisMap/yeneguzo-app/commit/e66058f9d2195507acd05dbcafdccf5b6ba4368a/checks?check_suite_id=396426493

You can have a look at the fastlane/ and .github/ folder in https://github.com/AddisMap/yeneguzo-app

How do we proceed? 

Probably I should document how to setup the GitHub actions with all the secrets on an own project.

@mdoelker What do you think?

**Comment by mdoelker** [comment]
Very cool! Yeah, that would be great if you could write down how that works. That is also useful for other projects that want to use that approach then.

**Comment by amenk** [comment]
1. Put the .github and fastlane folder into place (from yeneguzo-app repo)

* change apple_id (username) and app identifiers (also the apple_id for the app)

2. configure secrets at GitHub

androidSigningKeyAlias	written to settings.json
androidSigningKeyBase64	base 64 encoded .jks file, written to key file
androidSigningKeyPassword	password of the key, written to settings.json
androidSigningStorePassword	password of the store, written to settings.json
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD	this can be generated at the apple website - important: remove the hypens from the password
FASTLANE_PASSWORD	i think it is not needed, would be the AppleID password
MATCH_GIT_BASIC_AUTHORIZATION	base64 encoded github auth "user:token", used to clone the certificate repo
MATCH_PASSWORD	password for the fastlane match repo
 playStoreApiJsonBase64	play store API json file, encoded in base64

3. I am not very sure about the Xcode signing config. I seems you have to call `fastlane match` on your mac and then chose the keys match generated 

In theory that's it...

Somebody would have to test that.

In theory we also could automate the repo setup from an example/ folder a bit and ask for the information which is currently app-specific (or add a ENV file for that to make it truly universal)

**Comment by md-weber** [comment]
It would be great if we could add there a page to our Wiki & Readme.
https://github.com/trufi-association/trufi-core/wiki

**Comment by nicolelaine** [comment]
This issue should be part of each individual repo.

**Comment by amenk** [comment]
I don't fully agree, I think it would be super helpful to have at least a template for this in the main repo - to speed up deployments and builds for the trufi based apps.
