### ISSUE TITLE
Sorting destination list / priorities

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-core#360]
For Addis Ababa we got the following feedback:

> When choosing your starting point and destination there is a drop down list of various locations
> under the heading places, I would recommend putting major transit hubs or landmarks at the top > of the list (eg Merkato bus station,  stadium, megnanya, piazza, 4kilo, 6kilo)

Is there already a prioritization in search.json ? It's up for discussion how do implement that technically. For example we could prioritize specific OSM tags (such as place=suburb)

**Comment by mdoelker** [comment]
We could add a priority column to the search data that the client can sort by. This can be calculated based on different signals, for example the place you suggested.

**Comment by amenk** [comment]
Yes, other option would be to write the search.json as an ordered list (i.e. presorting it) -> would avoid sorting long lists in the app

**Comment by mdoelker** [comment]
Right, that can be done additionally. In the long run we want to take the sqlite output for better performance and space usage, but that has not been implemented on the client side yet :)

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
