### ISSUE TITLE
Always use landscape layout on tablets

### ISSUE THREAD

**Issue by mdoelker** [trufi-association/trufi-core#361]
Based on #271 and #308, we should consider to always use the landscape layout on iPads and other tables, as we have a lot more horizontal space in any orientation there.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/2145319/72223705-2f0ac400-3572-11ea-8191-3f013b6d6199.png)

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
