### ISSUE TITLE
Don't re-request location permission on decline

### ISSUE THREAD

**Issue by mdoelker** [trufi-association/trufi-core#367]
At the moment, when declining the permission request for location services, the app will re-request it immediately, so you end up in a loop. This only affects Android.

We should check where this happens and if we can prevent it, so that the user's wish is respected. At the same time, we need a proper error message should the user use "My location" as destination or origin (iOS), or re-request the permission when that option is selected (Android).

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
