### ISSUE TITLE
[COVID] As a passenger, I want to see the current load on public transport to decide if it is safe to travel

### ISSUE THREAD

**Issue by Melegy90** [trufi-association/trufi-core#370]
Gives user an overview of the load level on the network level.

FRONTEND:

When the user opens or activates the app, a backend services is called and the current network load is read. A short dialogue for the user is shown with a message depending on the load:
- "Most buses have capacity. Safe moment to travel. Take care!" when load < 40%
- "Be careful. Many buses are full right now." when load < 70%
- "Better not use bus now. Most buses are full right now." when load >= 70%

BACKEND:

**Requests:**

-  GET: getNetworkAverageLoad(lat, long)
Arguments:
lat, long: location of the user

Construct a "view" at the Traccar database level with average load for each network in the db for currently active trips

SELECT AVG(Load) from table WHERE timestamp BETWEEN now-10 minutes AND now GROUP BY busroute

Alternative Pseudo code (from melegy90):
1. use 'location' to get the nearest network/gtfs feed --> nearest_network
2. filter trips of 'nearest_network' by 'time' and 'status' (active/not active) --> filtered_trips
3. Get average of attribute 'load' from 'filtered_trips'

**Comment by ValorNaram** [comment]
Not implemented
