### ISSUE TITLE
[COVID] As a passenger, I want to report a bus driver that is not sticking to the rules, e.g. is overloading a bus, not sticking to routes

### ISSUE THREAD

**Issue by Melegy90** [trufi-association/trufi-core#371]
A way for users to report feedback on bus lines.

FRONTEND:

Add new button to Trufi App to report: https://material.io/resources/icons/?icon=report&style=baseline

When click on button, open new dialogue:
- What do you want to report?
   "Bus is full"
   "Bus is crowded"
   "Bus driver does not stick to route"
   "Other" => Let's the user write in the next dialogue.
   "Cancel/Back"

- The information is sent to a backend-server.

BACKEND:

- POST: setPassengerReport(location, time, lat, long, user_id, route_id, issue_code, user_notes)
Insert statement to the passenger reports table/document
Arguments:
issue_code: a standardized set of issue code to be agreed upon with one code for "other"
user_notes: open text for users to express qualitative information if they picked "other" as an issue code

For TEST, simply send email to feedback@trufi.app. However, if answer is "bus is full" or "bus is crowded" also call backend service from trufi app to inform Dashboard also that bus is full!

**Comment by ValorNaram** [comment]
Not implemented
