### ISSUE TITLE
[COVID] As a passenger, I want to see the current load on a specific bus line in order to see if I take that bus line

### ISSUE THREAD

**Issue by Melegy90** [trufi-association/trufi-core#372]
**Requests:**

- GET: getCurrentRouteLoad(route_id, time, n)
Get most recently departed (active) 'n' vehicles on the given route (n is sample size) using 'time' --> nearest_trips
Calculate average of 'nearest_trips' load

**Comment by ValorNaram** [comment]
Not implemented.
