### ISSUE TITLE
[COVID] As a passenger, I want to check-in and check-out to a bus to inform my friends where I am.

### ISSUE THREAD

**Issue by Melegy90** [trufi-association/trufi-core#375]
Full text: As a passenger, I want to check-in and check-out to a bus to inform my friends where I
am. I will inform Trufi about if the vehicle is loaded (=> IOT) so that they can calculate a
more accurate load
**Requests:**
First we need to filter a list of possible routes where the user is currently at so that they may choose the route from a list, for a better user experience

- GET: getNearestVehicle(location, n)
gets nearest vehicles (with route_id info for each vehicle) to the user --> nearest_routes
-----------------
Then the user chooses one option from the short-list --> current_route_id
- POST: checkInOutRoute(user_id, time, location, route_id, status)
route_id would be the current_route_id
status could be 1 (boarded) or 0 (alighted)

Note: for data integrity, status could be automatically switched to 0 if 'time' for boarding passes a specific threshold

**Comment by ValorNaram** [comment]
Not implemented.
