### ISSUE TITLE
Map shifts below routes when summary is open

### ISSUE THREAD

**Issue by mdoelker** [trufi-association/trufi-core#388]
When we open the summary, the map gets pushed up but the routes that overlay it do not. This seems to be a new behavior that we did not observe before. Might be related to a flutter_map update. We should restore the old behavior where the map and routes shift in alignment.

![image](https://user-images.githubusercontent.com/2145319/97678931-e25a9000-1a94-11eb-9ad4-b5269ce2b377.png)
![image](https://user-images.githubusercontent.com/2145319/97678951-e686ad80-1a94-11eb-8e30-6cb8b0c42a25.png)

**Comment by md-weber** [comment]
Could you elaborate a bit more, what exactly should shift? What would be the expected behaviour?

**Comment by mdoelker** [comment]
When the itinerary is opened, the overlay with the routes/lines shifts up as well

![image](https://user-images.githubusercontent.com/2145319/114888529-9c5a7400-9e09-11eb-8131-c2a6b05a1661.png)

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
