### ISSUE TITLE
Show departure time in result pane

### ISSUE THREAD

**Issue by christophhanser** [trufi-association/trufi-core#389]
Until now, TRUFI APP does not display the departure times and only minimal information on how to change transport.
Background is that in informal transport, where Trufi comes from, departure times are irrelevant. ;)
But for Trufi Bike App we need it, of course.

Please add departure time to the results. The information comes from the itenaries that OpenTripPlanner sends back.

![grafik](https://user-images.githubusercontent.com/10851343/97719392-4f871900-1ac7-11eb-8098-967b2b7c6bb6.png)

**Comment by nicolelaine** [comment]
Check this after the next update.

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
