### ISSUE TITLE
How to implement MapTiler key in "trufiCfg.map.mapTilerKey".

### ISSUE THREAD

**Issue by sjcr23** [trufi-association/trufi-core#394]
Following the guide on  **[trufi-core/example](https://github.com/trufi-association/trufi-core/tree/master/example)**

In the README, it says that once we get the Map Tiler Key, we should pass it in via the `trufiCfg.map.mapTilerKey` setting.

We noticed that the trufiCfg.* properties are being set on lib/main.dart, is that where the key value is usually added?

**Comment by md-weber** [comment]
Hi @sjcr23,

you will have two ways to add the MapTiler key, the first one is by directly adding it to the TrufiConfiguration in the main.dart in your host app (or the example app).

```dart
 TrufiConfiguration().map.mapTilerKey = "<Your-Map-Tiler-Key>";
```

This is a Singleton class that will be accessed inside of the Trufi Core. As an alternative, you are able to set that up inside of the `assets/cfg/app_config.json` which is in the .gitignore. In any case, you will need to overwrite it in your Host App.

```json
{
"mapTilerKey": "<Your-Map-Tiler-Key>" 
}
```

```dart
// Inside the main.dart
TrufiConfiguration().map.mapTilerKey = globalCfg.get("mapTilerKey");
```

Feel free to check the [How to use Trufi Core Guide](https://github.com/trufi-association/trufi-core/wiki/How-to-use-Trufi-Core)

Related Issues #395
