### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by md-weber** [trufi-association/trufi-core#398]
Null Safety would be beneficial to avoid bugs regarding Null statements. Dart supports that in the newest versions, and it would be helpful to use. We should first upgrade to Flutter 2.0 #397.

**Comment by md-weber** [comment]
Currently, we have only 4 non-null safe dependencies:

diff_match_patch - looks abandoned but there are some promising PR´s Maybe we have to switch to a fork.
https://github.com/jheyne/diff-match-patch

flutter_map - https://github.com/fleaflet/flutter_map/pull/870

Mockite and UUID are at the moment on lower versions but could be easily upgraded to ns

**Comment by aytunch** [comment]
I would love to see Trufi being updated to null safety too. @md-weber do you know if the 4 dependencies will be resolved soon? 
As a side note, once the dependencies are null-safe, please make a YouTube video for migrating Trufi to null safety :)

**Comment by ValorNaram** [comment]
Implemented
