### ISSUE TITLE
Sorting of the Places in the OfflineRequestManager behaves strange

### ISSUE THREAD

**Issue by md-weber** [trufi-association/trufi-core#416]
During my refactor in the OfflineRequestManager, I found an issue that the sorting is odd.

1. First the Results ar getting returned like that with the destinations.
<img width="934" alt="Screenshot 2021-04-17 at 17 50 10" src="https://user-images.githubusercontent.com/8026644/115118815-6520ca00-9fa5-11eb-9ad5-080b0b592a39.png">

2. First the Places are on high Priority, and then later at the sorting, the streets are high priority. Is that the correct behaviour?
3. There is also a problem with the take because we take the first `limit` elements, if there are only places we cut off all streets of the query. Should we not do something like the first half of the `limit` places and the second half of the `limit` are streets.
```dart
    // Combine Places and Street sort by distance
    List<LevenshteinObject<TrufiPlace>> sortedLevenshteinObjects = [
      ...queryPlaces, // High priority
      ...queryStreets // Low priority
    ]..sort((a, b) => a.distance.compareTo(b.distance));

    // Remove levenshteinObject
    final List<TrufiPlace> trufiPlaces = sortedLevenshteinObjects
        .take(limit)
        .map((LevenshteinObject<TrufiPlace> l) => l.object)
        .toList();

    // sort with street priority
    mergeSort(trufiPlaces, compare: (a, b) => (a is TrufiStreet) ? -1 : 1);
```

**Comment by nicolelaine** [comment]
Check if this is still happening after the next update.

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
