### ISSUE TITLE
💡 [Proposal] Change the SharedPreferences with a HiveDB

### ISSUE THREAD

**Issue by md-weber** [trufi-association/trufi-core#422]
Currently, we use the SharedPreferences, which are pretty slow compared to something like example HiveDB.

![grafik](https://user-images.githubusercontent.com/8026644/115354988-84447500-a1ba-11eb-813f-0bf9d611b6f5.png)

This could improve the overall performance of the application.

https://pub.dev/packages/hive

**Comment by mdoelker** [comment]
We hardly do any writes though, don't we? Are there any drawbacks?

**Comment by md-weber** [comment]
We currently write the whole "plan" into the local storage, which leads to a weird JSON Encoding and Decoding thing which costs some (not much) performance. At the moment it is ok, its just something to hit the 100 % 👍
