### ISSUE TITLE
Error on import your github repo

### ISSUE THREAD

**Issue by testwaretwics** [trufi-association/trufi-core#507]
Because every version of flutter_test from sdk depends on test_api 0.3.0 and test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19, flutter_test from sdk is incompatible with test >=1.16.0-nullsafety.19 <1.16.6.
And because bloc_test >=8.0.0-nullsafety.5 depends on test ^1.16.0 and test >=1.16.6 depends on webkit_inspection_protocol ^1.0.0, if flutter_test any from sdk and bloc_test >=8.0.0-nullsafety.5 then webkit_inspection_protocol ^1.0.0.
And because webkit_inspection_protocol >=1.0.0 depends on logging ^1.0.0 and latlong 0.6.1 depends on logging >=0.11.3 <1.0.0, one of flutter_test any from sdk or bloc_test >=8.0.0-nullsafety.5 or latlong 0.6.1 must be false.
And because no versions of latlong match >0.6.1 <0.7.0 and flutter_map 0.12.0 depends on latlong ^0.6.1, one of flutter_test any from sdk or bloc_test >=8.0.0-nullsafety.5 or flutter_map 0.12.0 must be false.
And because no versions of flutter_map match >0.12.0 <0.13.0 and trufi_core depends on flutter_map ^0.12.0, flutter_test from sdk is incompatible with bloc_test >=8.0.0-nullsafety.5.
So, because trufi_core depends on both bloc_test ^8.0.2 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because trufi_core depends on both bloc_test ^8.0.2 and flutter_test any from sdk, version solving failed.)

**Comment by nicolelaine** [comment]
This issue will be fixed in the next update.

**Comment by nicolelaine** [comment]
This issue will be fixed in the next update.
