### ISSUE TITLE
Separate additional map providers, like google maps from the core?

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-core#607]
**Is your feature request related to a problem? Please describe.**

A Trufi-core based app usually uses a fixed map provider.

Building the example from Trufi core is currently 32.2 MB

✓  Built build/app/outputs/flutter-apk/app-release.apk (32.2MB).

After removing Google maps:

✓  Built build/app/outputs/flutter-apk/app-release.apk (23.0MB).

This is a difference of 9,2MB or an increase of 39% after Google Maps was added to the core.

**Describe the solution you'd like**

I think there must be a more modular and object-oriented way to do this in flutter. But I am not a flutter expert, so I might be wrong.
There are lots of switch-cases in the code which return the right implementation for the interface.
Could we have a single generator / factory package which returns those interfaces, so adding a new map provider needs to be done only at one place?

So I am thinking of an additional flutter package `trufi-core-provider-google` (and `trufi-core-provider-maplibre` in the future), also we might extract `trufi-core-provider-leaflet` for the `flutter_map`. Then in the example one of those packages can be required and used.

**Describe alternatives you've considered**

Just leave it as it is and live with the bigger apk size. 

**Additional context**

I tried to add maplibre-gl support and was wondering if we keep adding and adding new map providers, the core-application might grow too much.

I am also wondering why we need Google maps though as I thought / prefer we are focusing on open data :-)

I believe trufi-core based apps are also often deployed to developing countries where older / more affordable mobiles might be used and where space-consumption matters.

**Comment by ValorNaram** [comment]
@SamuelRioTz @GustavoTCh Planned is something like

- Put your `MapProviderService` in a specified directory
- Import it in `MapProviderCollection` and make it the default and only one map provider

Right?

**Comment by amenk** [comment]
I think this was solved by @GustavoTCh in https://github.com/trufi-association/trufi-core/pull/608

Some more information would be appreciated. How can new map providers be added now in the new structure?
