### ISSUE TITLE
GPS Direction Feature

### ISSUE THREAD

**Issue by Denis306** [trufi-association/trufi-core#609]
As a user I want the map to follow my gps and change perspectives to make my journey experience even more comfortable.

**Comment by Denis306** [comment]
@SamuelRioTz I need input on this

**Comment by ZihRah** [comment]
Currently, the flutter_map package does not have access to the rotation data, it is difficult to create a compass function, we must wait for an update of flutter_map where the data is provided.

**Comment by ZihRah** [comment]
The app has to be tested.

**Comment by GustavoTCh** [comment]
I've done some testing and it works fine.
