### ISSUE TITLE
Basic Push Notifications New features 2

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/trufi-core#618]
"As Trufi eV, we want to push notifications about new server-side features to the user (or other news).
TO BE DISCUSSED: And inform the same way about new client-side features like Spiegel Online does (check Slack)"

**Comment by leoguti** [comment]
Is this functionality related to route changes, e.g. closed routes or schedule changes?

**Comment by leoguti** [comment]
What are the notification categories?

**Comment by ZihRah** [comment]
We will wait for Stadt Navi as they will implement it and will be paid.
