### ISSUE TITLE
Adding the fares in Trufi for CBBA

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/trufi-core#675]
The fares will be shown to the respective routes.

**Comment by AnivlisLuz** [comment]
[Option content](https://docs.google.com/document/d/1GU9TX7DrFMKvVoxVoQqzzPrMARYpIwq_2VU9PjODeDU/edit?usp=sharing)

**Comment by AnivlisLuz** [comment]
The final desing is [here](https://www.figma.com/file/ggRtaFHMYfsdBOobOEWpg1/TRUFI---App?type=design&node-id=0-1&mode=design&t=4ewqFZps99iTbqAF-0).
